server:
  port: 8023
spring:
  application:
    name: mq-stream-consumer
  rabbitmq:
    password: admin
    username: admin
    host: 193.112.82.144
    port: 5672
  cloud:
    stream:
      bindings:
        userMsg-consumer:
          group: user
          # 普通消息目标交换机名称
          destination: userMsg-exchange
          consumer:
            max-attempts: 3 # 消费尝试次数，默认值为3。设置为1 代表不重试
            back-off-initial-interval: 1000 # 消息消费失败后重试消费消息的初始化间隔时间。默认1s，即第一次重试消费会在1s后进行
            back-off-multiplier: 5 # 相邻两次重试之间的间隔时间的倍数。默认2，即第二次是第一次间隔时间的2倍，第三次是第二次的2倍
            back-off-max-interval: 10000 # 下一次尝试重试的最大时间间隔，默认为10000ms，即10s。
        # Spring Cloud Stream 通道名称
        userMsg-delay-consumer:
          group: group1
          # 延迟消息的目标交换机名称
          destination: user-delay-msg-exchange
          consumer:
            max-attempts: 3 # 消费尝试次数，默认值为3。设置为1 代表不重试
            back-off-initial-interval: 1000 # 消息消费失败后重试消费消息的初始化间隔时间。默认1s，即第一次重试消费会在1s后进行
            back-off-multiplier: 5 # 相邻两次重试之间的间隔时间的倍数。默认2，即第二次是第一次间隔时间的2倍，第三次是第二次的2倍
            back-off-max-interval: 10000 # 下一次尝试重试的最大时间间隔，默认为10000ms，即10s。
      rabbit:
        # 利用Spring Cloud Stream的延时特性配置延迟消息队列
        bindings:
          userMsg-delay-consumer:
            consumer:
              delayedExchange: true
              autoBindDlq: true
              republishToDlq: true
              dlqTtl: 1296000000
